const cfg=window.APP_CONFIG||{};const form=document.getElementById('loginForm');const statusEl=document.getElementById('status');const painel=document.getElementById('painel');const acesso=document.getElementById('acesso');const modulosEl=document.getElementById('modulos');const usuarioNome=document.getElementById('usuarioNome');const btnSair=document.getElementById('btnSair');const btnEntrar=document.getElementById('btnEntrar');const btnAluno=document.getElementById('btnAluno');const btnAdmin=document.getElementById('btnAdmin');const codigoEl=document.getElementById('codigo');let perfil='ALUNO';
function setStatus(msg,erro=false){statusEl.textContent=msg||'';statusEl.className='status '+(erro?'erro':'ok')}
function setPerfil(p){perfil=p;const admin=p==='ADMIN';btnAdmin.className=admin?'active':'alt';btnAluno.className=admin?'alt':'active';codigoEl.value=admin?'admin':'';codigoEl.focus()}
btnAluno.addEventListener('click',()=>setPerfil('ALUNO'));btnAdmin.addEventListener('click',()=>setPerfil('ADMIN'));
function api(payload){return new Promise((resolve,reject)=>{if(!cfg.API_URL){reject(new Error('Backend não configurado.'));return}const requestId='wa_'+Date.now()+'_'+Math.random().toString(36).slice(2);const iframe=document.createElement('iframe');iframe.name=requestId;iframe.style.display='none';document.body.appendChild(iframe);const f=document.createElement('form');f.method='POST';f.action=cfg.API_URL;f.target=requestId;f.style.display='none';const input=document.createElement('input');input.type='hidden';input.name='payload';input.value=JSON.stringify({...payload,requestId});f.appendChild(input);document.body.appendChild(f);let done=false;const cleanup=()=>{window.removeEventListener('message',onMessage);try{f.remove()}catch(_){}setTimeout(()=>{try{iframe.remove()}catch(_){}},100)};const onMessage=ev=>{if(done)return;let data=ev.data;try{if(typeof data==='string')data=JSON.parse(data)}catch(_){}if(!data||data.requestId!==requestId)return;done=true;clearTimeout(timer);cleanup();resolve(data.response||data)};window.addEventListener('message',onMessage);const timer=setTimeout(()=>{if(done)return;done=true;cleanup();reject(new Error('Sem resposta do backend. Verifique a implantação do Apps Script e a permissão de acesso.'))},20000);f.submit()})}
function renderUsuario(u){acesso.classList.add('hidden');painel.classList.remove('hidden');usuarioNome.textContent=u?.nome||'Usuário';modulosEl.innerHTML='';(u?.modulos||[]).forEach(m=>{const d=document.createElement('div');d.className='modulo';d.textContent=m.nome||'Módulo';modulosEl.appendChild(d)})}
form.addEventListener('submit',async e=>{e.preventDefault();btnEntrar.disabled=true;setStatus('Validando...');try{const r=await api({acao:'login',codigo:codigoEl.value.trim(),senha:document.getElementById('senha').value,perfil});if(!r?.ok)throw new Error(r?.erro||'Credenciais inválidas.');sessionStorage.setItem('wa_token',r.token||'');sessionStorage.setItem('wa_usuario',JSON.stringify(r.usuario||{}));renderUsuario(r.usuario||{})}catch(err){setStatus(err.message||'Erro ao entrar.',true)}finally{btnEntrar.disabled=false}});
btnSair.addEventListener('click',async()=>{const token=sessionStorage.getItem('wa_token');try{if(token)await api({acao:'logout',token})}catch(_){}sessionStorage.clear();painel.classList.add('hidden');acesso.classList.remove('hidden');form.reset();setPerfil('ALUNO');setStatus('')});
(async()=>{const token=sessionStorage.getItem('wa_token');if(!token)return;try{const r=await api({acao:'validarSessao',token});if(r?.ok)renderUsuario(r.usuario||{})}catch(_){sessionStorage.clear()}})();
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=5').then(r=>r.update&&r.update()).catch(()=>{}))}
